### ISSUE TITLE
Make list view display commutes in groups: Evening / Morning

### ISSUE THREAD

**Issue by aranasaurus** [aranasaurus/CommuteLog#13]
Or could be Home and Work or 🏠->💼 or some such.

**Comment by aranasaurus** [comment]
Let's move this conversation (https://github.com/aranasaurus/CommuteLog/pull/16#issuecomment-433588015) over to here

**Comment by aranasaurus** [comment]
As you were mentioning [here](https://github.com/aranasaurus/CommuteLog/pull/18#issuecomment-433756151) you'll probably be adding to CommuteManager's `fetchCommutes()` function to support this. I'd think adding a parameter to the method to take a `CommuteSchedule` would probably work 🤔 something like `fetchCommutes(for schedule: CommuteSchedule, ascending: Bool = false)`

**Comment by toastersocks** [comment]
I just noticed this. Sounds good. 👍 I should have something up this week. Probably tomorrow.
